GET http://localhost:7007/hotel/



###
GET http://localhost:7007/hotel/12
Accept: application/json
Content-Type: application/json


###
POST http://localhost:7007/hotel/
Content-Type: application/json

{
    "id": 11,
  "name": "Rasmussi's Palace",
     "address": "Minvej 22",
     "description": "The worst hotel in the world"
}

###
PUT http://localhost:7007/person/2

{
  "name": "Jimmi",
  "age": 19

}


###
POST http://localhost:7007/room/
Content-Type: application/json

{
  "id": 11,
  "roomNumber": 22,
  "hotelId": 6,
  "price": 2999,
    "description": "The best room in the world"
}